name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake

    - name: Install Buildozer and python-for-android
      run: |
        pip install buildozer cython python-for-android

    - name: Pre-accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        # 设置环境变量强制接受许可证
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        yes | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --licenses || true
        # 如果上面失败，尝试手动设置接受的许可证
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-googletv-license
        echo "601085b94cd77f0b54ff86406957099ebe79c4d6" > $ANDROID_SDK_ROOT/licenses/android-sdk-arm-dbt-license

    - name: Build APK
      run: |
        # 设置环境变量
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b
        # 构建
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
        retention-days: 7
