name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Flet
      run: pip install flet
      
    - name: Build APK with Flet
      run: flet build apk
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flet-apk
        path: build/apk/*.apk
        retention-days: 7
