name: Build Flet APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Flet
      run: pip install flet
      
    - name: Create Flet config
      run: |
        echo "name: 青芜识界" > flet.yaml
        echo "description: 植物识别与收藏应用" >> flet.yaml
        echo "publish_to: none" >> flet.yaml
      
    - name: Build APK with Flet
      run: flet build apk --module-name main.py
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flet-apk
        path: build/apk/*.apk
        if-no-files-found: ignore
        retention-days: 7
