name: Build APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install buildozer
        buildozer -v android debug
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
