name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build with Buildozer
      uses: artem-ryabov/buildozer-action@v1
      with:
        work-dir: .
        buildozer-version: stable
    - uses: actions/upload-artifact@v4
      with:
        name: APK
        path: "bin/*.apk"
